chat-app/codebase/chat-app/config/routes.rb
Rails.application.routes.draw do
  namespace :api do
  namespace :v1 do
    namespace :authentication do
      get 'users/sign_up'
      end
    end
  end

  get 'api_help/index'

  devise_for :users, :controllers => {:sessions => "sessions", omniauth_callbacks: 'omniauth_callbacks'}
  root 'home#index'

  namespace :api, :defaults => {:format => 'json'} do
    scope :module => :v1 do      
      namespace :authentication do
        post 'login'  => 'sessions#create', :as => :login
        get  'logout' => 'sessions#destroy', :as => :logout
        post 'forgot_password' => 'passwords#create', :as => :forgot_password
        post 'change_password' => 'passwords#change_password', :as => :change_password
        post 'sign_up' => "users#sign_up",:as => :signup
        get  'get_content' => "users#get_content", :as => :get_content
        post 'send_friend_request' => "users#send_friend_request", :as => :send_friend_request
        post 'confirm_friend_request' => "users#confirm_friend_request", :as => :confirm_friend_request
        post 'set_translation' => "users#set_translation", :as => :set_translation
      end
    end
  end
end

chat-app/codebase/chat-app/app/views/layouts/api_help.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>API Help</title>
    <%= stylesheet_link_tag    "api_help", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "api_help", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <div id="content">
      <%= yield %>
    </div>  
  </body>
</html>

chat-app/codebase/chat-app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "ChatApp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

<div class="container">
  <div class="row clearfix">
    <div class="col-md-12 column">
      <nav class="navbar navbar-default" role="navigation">
        <div class="navbar-header">
           <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"> <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button> <a class="navbar-brand" href="<%= root_path %>"><%= current_user.present? ? current_user.full_name : "Chat APP" %></a>
          </div>                
          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li>
                <a href="<%= api_help_index_path %>">API Doc</a>
              </li>
<!--               <li>
                <a href="<%#= user_omniauth_authorize_path("facebook") %>"> fConnect</a>
              </li> -->
              <li class="dropdown">
                 <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown<strong class="caret"></strong></a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="#">Action</a>
                  </li>
                  <li>
                    <a href="#">Another action</a>
                  </li>
                  <li>
                    <a href="#">Something else here</a>
                  </li>
                  <li class="divider">
                  </li>
                  <li>
                    <a href="#">Separated link</a>
                  </li>
                  <li class="divider">
                  </li>
                  <li>
                    <a href="#">One more separated link</a>
                  </li>
                </ul>
              </li>
            </ul>
            <form class="navbar-form navbar-left" role="search">
              <div class="form-group">
                <input type="text" class="form-control">
              </div> <button type="submit" class="btn btn-default">Submit</button>
            </form>
            <ul class="nav navbar-nav navbar-right">
              <li>
                <% if current_user.present? %>
                  <div class="navbar-collapse collapse">
                    <!-- menu items gets rendered here instead -->
                    <ul class="nav navbar-nav navbar-right" style="margin-right:10px;">
                      <li><a href="<%= destroy_user_session_path%>" data-method='delete'>Logout</a></li>
                    </ul>
                  </div>
                <% else %>
                  <div class="navbar-collapse collapse">
                    <li><a class="btn" data-toggle="modal" data-target="#myModal" onclick="reset();">
                      Login
                    </a></li>
                    <li><%= link_to "Sign Up", "#" %></li>
                    <!-- Modal -->
                    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                      <div class="modal-dialog" style="width: 370px !important;">
                        <div class="modal-content" style="border-radius: 0px !important;">
                          <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-hidden="true" style="margin-top: 12px !important;">&times;</button>
                            <h4 class="modal-title" id="myModalLabel" style="text-align: center;font-size: 30px;"> Sign In </h4>
                          </div>
                          <div class="modal-body">

                          </div>
                          <div class="modal-footer">
                            <button id="close" type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                <% end %>
              </li>
            </ul>
          </div>        
        </nav>
        <%= render '/shared/flash_messages' %>
        <%= yield %>
      </div>
    </div>
  </div>
 </body>
</html>